### ISSUE TITLE
Add another signer for the minting

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/minting_v3#12]
Would be good to have a back up signer just in case, so we don't have to annoy people during holidays or things like that.
I suggest to add Peter vd Henst

@LeeSmet pls help Peter install js, after this he can be added to the signers.

**Comment by LeeSmet** [comment]
@sabrinasadik this repo is for the actual logic of V3 minting, higher lvl issues such as this one (adding a signer) should probably go to either the repo containing the actual implementation of TFT on stellar (https://github.com/threefoldfoundation/tft), or a general repo (such as home). As for the installation of js, that is definitely out of scope of this repo.

**Comment by sabrinasadik** [comment]
Ok my bad! Closing this one
