### ISSUE TITLE
Apply latest GEP

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/minting_v3#30]
Things which need to happen in the minting:

- Minimum uptime requirement enforced:
  - 95% for DIY nodes
  - 98% for certified nodes
  Uptime is currently overruled to be linear for both these types of nodes. It is not described what the payout is for nodes which meet this threshold. The intuitive approach is to continue paying linearly once the threshold is met, since we still want to reward people for having their node online (paying out the full amount once nodes are up for the threshold duration means the farmer is incentivized to just turn of his node the last day of the period for a DIY node in case he has no prior downtime in the period).
- Proof of utilization revenues: cost of deployment being distributed is handled completely on chain, no minting action needed. Interestingly there is a technical loophole now since IP and pub network is billed to users but also rewarded from minting side, which leads to the total combined IP/pub network reward being higher than the cost.
- Allow 1 30 minute wakup violation before slashing the full month
  This could be implemented with a counter on the node struct for these specific incidents, which after the processing gets converted to the appropriate violation
- 1B minting cap: while we technically could get the current supply of TFT  and TFTA on stellar, this is not a reproducible action, so for now we will keep this outside of the code and manually verify every month. Additionally, it is not clearly defined what happens when a minting round would put us past 1B TFT
- TFT Burning stops: This is handled on tfchain.

**Comment by sabrinasadik** [comment]
Problem: farmers that are using their own public ip's /network, earn more tokens than they pay due to the 50% deployment cost + the fact that public ip's/network being used adds additional rewards to the minting.
