### ISSUE TITLE
Farmerbot nodes not credited with standby time at end of period

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/minting_v3#33]
Since the start of uptime SLA enforcement, farmers are asking for more detail about what caused their nodes not to reach the requirement, especially in the case of farmerbot usage.

While investigating some of these cases, I noticed gaps between the loss of uptime that could be attributed to identifiable events (nodes failing to wake up within the 24 hour and 30 minute limits) and the missing uptime according to minting.

What does fit into those gaps is the time that these nodes spent standby immediately before the end of the period. Reading the minting code I don't see any measure in place to credit this time. Since there is no processing of power target change events in the post period, the only nodes that can receive uptime credit after being standby when the period ends are nodes that already had a wake up initiated before the end of the period.

The outcome of this is that practically every node managed by the farmerbot has no chance to earn its final 0 to ~23.5 hours of uptime in each period. This can easily mean the difference between minting and not minting at all with the uptime SLA in place, especially for certified nodes which are only allowed about 14 hours of downtime each period. Given that rewards are still scaled linearly with achieved uptime, this also means some loss of rewards for nodes that did mint.

**Comment by sabrinasadik** [comment]
We're looking into this. Will discuss with the team what to do after fixing the minting code.

**Comment by sabrinasadik** [comment]
See https://forum.threefold.io/t/minting-may-2024/4373

Will be fixed beginning of July
